### PR TITLE
Added preliminary password argument support. Needs testing

### PR DESCRIPTION
**Pull request by RazeLighter777**
Sorry for any improper practices, but I tried to keep it as well-documented and clean as possible.  (I am a C++ not a C programmer)

### CODE REVIEW

**Comment by fangfufu** [comment]
Sorry I am going to have to reject this pull request - I don't like the part where you force the link into HTTP link. Also you didn't follow my indentation style - I used 1TBS (https://en.wikipedia.org/wiki/Indentation_style#1TBS). I know it sounds harsh, but I know bigger software projects who reject patches due to indentation issues, e.g lcdproc. 

Finally I was hoping that you somehow parsed username / password as an option to libcurl, rather that modifying the URL. 

Thank you for your contribution though, this gives me an excellent idea on how to implement your feature request.

**Comment by RazeLighter777** [comment]
OK. If you want you can just use the argument parsing code. But keep in mind that fuse doesn't like the -p and -u options, so you have to remove them before you pass them in.  :)

I can probably fix the http thing fairly quickly

I don't know anything about libcurl or fuse at all, so I couldn't touch any of that. I'm going to keep my fork though, since it is useful to me. (I am setting up a network drive mounted on a server in Ohio)

Sorry about the formatting. I forgot to change some settings in my IDE.

Do you want me to keep working on it? Just tell me if there is anything I can do to help.

**Comment by fangfufu** [comment]
What do you mean by "fuse doesn't like the -p and -u options"? I know fuse does have its own parser, do you mean fuse parser just reject them? Or does fuse also take -p and -u option for something else? 

Yes, please keep working on it. If you fix the indentation issue and the https issue, I am happy to merge it. Although I might change your code later on. :)

**Comment by fangfufu** [comment]
Also please don't use this for production purposes. I don't actually know how stable it is. I know HTTPS still makes it crash. 

Finally why do you need to pass in -p and -u options? All your code does is modifying the URL anyway. Can't you just modify the URL in the program / script that calls this program?

**Comment by fangfufu** [comment]
superseded under issue #8

**Pull request closed without merging**
